env: development
port: 7777
mysql:
  dbhost: localhost
  dbuser: root
  dbport: 3306
  dbpass: \#Wahyu123
  dbname: account
jwt:
  signing_key: your_secret_key
  exp: 1440     # * a minutes
redis:
  host: localhost:6379
  pass:
  db: 0
