env: development
port: 6666
mysql:
  dbhost: localhost
  dbuser: root
  dbport: 3306
  dbpass: "#Wahyu123"
  dbname: account
jwt:
  signing_key: your_secret_key
  exp: 24h
redis:
  host: localhost:6379
  pass:
  db: 0
